<a href="https://colab.research.google.com/github/Sanjay400/InternTask3/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
data = pd.read_csv('/content/CarPrice.csv')
data.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [8]:
data.shape[0]

205

In [10]:
data.isna().sum() / data.shape[0]

car_ID              0.0
symboling           0.0
CarName             0.0
fueltype            0.0
aspiration          0.0
doornumber          0.0
carbody             0.0
drivewheel          0.0
enginelocation      0.0
wheelbase           0.0
carlength           0.0
carwidth            0.0
carheight           0.0
curbweight          0.0
enginetype          0.0
cylindernumber      0.0
enginesize          0.0
fuelsystem          0.0
boreratio           0.0
stroke              0.0
compressionratio    0.0
horsepower          0.0
peakrpm             0.0
citympg             0.0
highwaympg          0.0
price               0.0
dtype: float64

In [11]:
data.duplicated().sum()

0

In [12]:
data.describe(include=object)

CarName fueltype aspiration doornumber carbody drivewheel  \
count             205      205        205        205     205        205   
unique            147        2          2          2       5          3   
top     toyota corona      gas        std       four   sedan        fwd   
freq                6      185        168        115      96        120   

       enginelocation enginetype cylindernumber fuelsystem  
count             205        205            205        205  
unique              2          7              7          8  
top             front        ohc           four       mpfi  
freq              202        148            159         94

In [14]:
data.drop(columns = 'car_ID', inplace = True)

In [15]:
data['symboling'].unique()

array([ 3,  1,  2,  0, -1, -2])

In [16]:
category_column = data.select_dtypes(include= object).columns.tolist()

In [17]:
category_column

['CarName',
 'fueltype',
 'aspiration',
 'doornumber',
 'carbody',
 'drivewheel',
 'enginelocation',
 'enginetype',
 'cylindernumber',
 'fuelsystem']

In [18]:
numerical_col = data.select_dtypes(exclude=object).columns.tolist()

In [19]:
numerical_col

['symboling',
 'wheelbase',
 'carlength',
 'carwidth',
 'carheight',
 'curbweight',
 'enginesize',
 'boreratio',
 'stroke',
 'compressionratio',
 'horsepower',
 'peakrpm',
 'citympg',
 'highwaympg',
 'price']

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for column in category_column:
    data[column] = le.fit_transform(data[column])

In [21]:
data.sample(3)

symboling  CarName  fueltype  aspiration  doornumber  carbody  \
85           1       67         1           0           0        3   
176         -1      115         1           0           0        3   
68          -1       17         0           1           0        4   

     drivewheel  enginelocation  wheelbase  carlength  ...  enginesize  \
85            1               0       96.3      172.4  ...         122   
176           1               0      102.4      175.6  ...         122   
68            2               0      110.0      190.9  ...         183   

     fuelsystem  boreratio  stroke  compressionratio  horsepower  peakrpm  \
85            1       3.35    3.46               8.5          88     5000   
176           5       3.31    3.54               8.7          92     4200   
68            3       3.58    3.64              21.5         123     4350   

     citympg  highwaympg    price  
85        25          32   6989.0  
176       27          32  10898.0  
68        22          25  28248.0  

[3 rows x 25 columns]

In [22]:
drop_cols = ['symboling', 'fueltype', 'doornumber', 'enginelocation', 'fuelsystem', 'stroke', 'compressionratio']

data.drop(columns = drop_cols, inplace = True)

In [23]:
data.head()

CarName  aspiration  carbody  drivewheel  wheelbase  carlength  carwidth  \
0        2           0        0           2       88.6      168.8      64.1   
1        3           0        0           2       88.6      168.8      64.1   
2        1           0        2           2       94.5      171.2      65.5   
3        4           0        3           1       99.8      176.6      66.2   
4        5           0        3           0       99.4      176.6      66.4   

   carheight  curbweight  enginetype  cylindernumber  enginesize  boreratio  \
0       48.8        2548           0               2         130       3.47   
1       48.8        2548           0               2         130       3.47   
2       52.4        2823           5               3         152       2.68   
3       54.3        2337           3               2         109       3.19   
4       54.3        2824           3               1         136       3.19   

   horsepower  peakrpm  citympg  highwaympg    price  
0         111     5000       21          27  13495.0  
1         111     5000       21          27  16500.0  
2         154     5000       19          26  16500.0  
3         102     5500       24          30  13950.0  
4         115     5500       18          22  17450.0

In [25]:
X = data.iloc[:, :-1].values
y = data.iloc[:, -1].values

In [26]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=2)

In [27]:
X_train

array([[6.80e+01, 0.00e+00, 2.00e+00, ..., 5.50e+03, 3.10e+01, 3.80e+01],
       [9.00e+00, 0.00e+00, 3.00e+00, ..., 5.50e+03, 1.90e+01, 2.50e+01],
       [1.43e+02, 1.00e+00, 3.00e+00, ..., 5.10e+03, 1.70e+01, 2.20e+01],
       ...,
       [2.30e+01, 0.00e+00, 0.00e+00, ..., 4.75e+03, 1.60e+01, 1.80e+01],
       [1.30e+01, 0.00e+00, 3.00e+00, ..., 5.40e+03, 1.60e+01, 2.20e+01],
       [1.15e+02, 0.00e+00, 1.00e+00, ..., 4.80e+03, 2.40e+01, 3.00e+01]])

In [28]:
y_test

array([ 6692.   , 14489.   ,  9549.   , 16430.   , 13415.   ,  6695.   ,
       18280.   , 18344.   ,  7775.   ,  9988.   , 12964.   ,  6918.   ,
        7975.   , 21105.   , 15040.   ,  7299.   ,  8238.   ,  7295.   ,
       34028.   ,  6229.   ,  7957.   ,  8916.5  , 17710.   , 20970.   ,
       11245.   ,  5151.   ,  7198.   ,  8948.   , 17669.   , 16500.   ,
       13645.   , 13950.   ,  6229.   , 24565.   ,  8916.5  , 16558.   ,
       16695.   , 15998.   , 13845.   ,  7995.   , 15580.   , 34184.   ,
       17859.167,  5572.   , 10698.   ,  7463.   ,  7395.   ,  7603.   ,
        7609.   ,  9989.   , 35550.   , 10345.   ,  7126.   ,  7775.   ,
       22625.   , 12440.   , 15750.   , 18399.   ,  8921.   , 12945.   ,
        5499.   ,  9233.   ])

In [29]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)

In [30]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor()

In [31]:
regressor.fit(X_train, y_train)

RandomForestRegressor()

In [32]:
prediction = regressor.predict(X_test)
prediction

array([ 7219.92 , 13837.45 ,  9207.19 , 14483.6  , 15341.86 ,  6735.49 ,
       14212.25 , 10996.04 ,  8690.2  , 11071.51 , 14364.78 ,  8007.51 ,
        8496.21 , 14955.94 , 12465.4  ,  7074.79 ,  8045.98 ,  7330.95 ,
       33348.025,  6749.38 ,  8005.56 ,  6572.5  , 18740.01 , 15341.67 ,
        9322.99 ,  5952.2  ,  7673.54 , 10455.09 , 12038.3  , 14806.12 ,
       12074.95 , 12135.04 ,  6640.38 , 15231.91 ,  6512.82 , 17333.92 ,
       15524.09 , 17319.09 , 11380.02 ,  8744.05 , 15584.72 , 36873.61 ,
       19225.45 ,  5699.95 , 10589.76 ,  8746.58 ,  6824.76 ,  7844.67 ,
        7908.22 , 10023.13 , 34496.83 ,  9471.88 ,  8333.94 ,  8465.4  ,
       18892.36 , 15458.01 , 15587.07 , 17623.32 ,  9972.32 , 12025.61 ,
        7160.92 , 10832.89 ])

In [33]:
from sklearn.metrics import mean_absolute_error,r2_score

In [34]:
mean_absolute_error(y_test, prediction)

1593.6391612903224

In [35]:
r2_score(y_test, prediction)

0.8745256510577859